/* =========================
   PERSONALIZATION / CONTENT
   ========================= */
const SITE={
 herName:'Samridhi',birthday:'26/09/2007',music:'',
 qualities:[
  {title:'Your eyes',text:"I don't think you realise how much I love your eyes. There’s just something about them that makes it impossible for me not to stare."},
  {title:'Your cuteness',text:"The funniest part is that you don't even realise how cute you are sometimes. Your little expressions, your smile, and the way you react when I tease you are some of my favourite things."},
  {title:'The way you laugh',text:'I love seeing you laugh, especially when I’m the reason for it. Sometimes annoying you is completely worth it just to see that smile.'},
  {title:'Our little moments',text:'It’s never really been about the big things. It’s the random conversations, the teasing, the little fights, and those moments when we’re just comfortable being around each other.'},
  {title:"Domino's & the library",text:'Somehow Domino’s and the library became our little playground. From me teasing you nonstop to holding your hands, pulling you closer, and annoying you just enough to make you laugh… those tiny moments are some of my favourites.'},
  {title:'Simply you',text:'More than anything, I love you for being you. Somewhere along the way, you became someone I care about more deeply than I ever expected.'}
 ],
 timeline:[
  {label:'2007',title:'The beginning',text:'I had no idea back then how important you would eventually become to me. You were simply someone in my life, and I never imagined our story would turn into what it is today.'},
  {label:'SOMEWHERE ALONG THE WAY',title:'You became more than a friend',text:'You were first a friend — someone I slowly started getting closer to. And without really noticing when it happened, my feelings started changing. You became someone I wanted more of in my life.'},
  {label:'10 JULY 2025',title:'The day I realised',text:'If I had to choose the day when I realised I genuinely liked you, it would be 10 July 2025. What started as a simple feeling slowly became something much, much bigger.'},
  {label:'SINCE THEN',title:'Everything in between',text:'Since that day, there have been so many conversations, laughs, little fights, memories, teasing, and moments together. Somewhere between all of them, you became one of the biggest parts of my life.'},
  {label:'TODAY',title:'Why I made this',text:'I could have just sent you a birthday message. But you’re important enough to me that I wanted to make something you could actually keep — something that says the things I sometimes struggle to say out loud.'}
 ],
 cards:[
  {front:'A little memory',tag:'01',back:'Domino’s, the library, annoying you until you laugh, holding your hands and pulling you closer… somehow those little moments became some of my favourites. ❤️'},
  {front:'Something I’ve noticed',tag:'02',back:"You probably don't realise how cute you look when you're not trying to be. The little expressions you make when I tease you are honestly one of my favourite things."},
  {front:'Something honest',tag:'03',back:'I think a part of me knew this was becoming something more long before I actually admitted it to myself.'}
 ],
 letter:`Dear Samridhi,\n\nHappy Birthday. ❤️\n\nI honestly didn't want to make this just another birthday message that you read, smile at, and then forget.\n\nI wanted to make something that actually meant something.\n\nYou were first a friend — someone I slowly got closer to without realising how important you would eventually become to me.\n\nSomewhere along the way, that changed.\n\nI started liking you as more than just a friend.\n\nAnd if I had to point to one day when I first realised that, I'd say 10 July 2025.\n\nBut honestly, what happened after that is what made those feelings grow.\n\nThe random conversations.\nThe teasing.\nThe little fights.\nThe laughs.\nThe time at Domino’s.\nThe library.\nHolding your hands.\nPulling you closer.\nAnnoying you just enough to make you laugh.\n\nAll those little things probably don't seem like a big deal individually, but they're some of the moments I remember the most.\n\nAnd then there are the things about you that I don't think I'll ever get tired of.\n\nYour eyes.\nYour smile.\nYour laugh.\nThe way you get cute without even realising it.\n\nBut it's not just about those things.\n\nIt's about you.\n\nYou've slowly become one of the biggest and most important parts of my life, and I honestly don't know if I've ever properly explained what that means to me.\n\nYou already know that I like you.\n\nAnd I know there are feelings on your side too.\n\nMaybe we're not ready to call this a relationship yet. Maybe you're not ready to say everything out loud.\n\nAnd that's okay.\n\nI'm not making this to put pressure on you.\n\nI'm making this because today is your birthday, and I wanted you to know what's been sitting at the bottom of my heart for a long time.\n\nYou mean a lot to me, Samridhi.\n\nMore than I probably know how to explain.\n\nSo before you reach the end of this, there's just one thing left for me to say...\n\n❤️`,
 confessionLines:['I wanted your birthday to be special.','But honestly, that’s not the only reason I made this.','There’s something I’ve wanted to tell you for a long time.','Something that started on 10 July 2025.','And somewhere along the way, it became much bigger than I expected.'],
 confession:`Samridhi, I really, really like you.\n\nWhat started on 10 July 2025 as me simply liking you slowly turned into something I can't really put into words.\n\nSomewhere between all our conversations, the teasing, the laughs, the little fights, Domino’s, the library, and all those random moments together, you became one of the most important people in my life.\n\nYou already know that I like you. You probably know it better than I think you do.\n\nAnd I know there’s something between us too.\n\nMaybe we’re not ready to give it a name yet, and I completely respect that.\n\nI’m not asking you to give me an answer today.\n\nI don’t want to rush you into anything.\n\nI just want you to know how I feel.\n\nI like you not just because you’re cute, not just because of your eyes or your smile, but because of who you are and because of how you make my life feel different just by being a part of it.\n\nSo if someday you’re ready to choose someone...\n\nI hope you’ll choose me.\n\nBecause if it’s you, I’m willing to wait. ❤️`,
 permission:"You don't have to say anything right now. You don't have to give me an answer today. I just wanted you to know how much you mean to me.",finalMessage:'Happy Birthday, Samridhi. ❤️\n\n— Neel Gupta'
};
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
q('#herName')?.remove();q('#letterName')?.remove();
q('#letterBody').textContent=SITE.letter;q('#permission').textContent=SITE.permission;q('#birthdayEnd').textContent=SITE.finalMessage;
q('#qualities').innerHTML=SITE.qualities.map((x,i)=>`<article class="memory reveal"><div class="n">0${i+1}</div><h3>${x.title}</h3><p>${x.text}</p></article>`).join('');
q('#timelineList').innerHTML=SITE.timeline.map(x=>`<article class="milestone reveal"><div class="dot"></div><div><small>${x.label}</small><h3>${x.title}</h3><p>${x.text}</p></div></article>`).join('');
q('#messageCards').innerHTML=SITE.cards.map(x=>`<article class="card reveal" tabindex="0" role="button" aria-label="Open ${x.tag}"><div class="card-inner"><div class="card-face card-front"><span class="tag">${x.tag}</span><h3>${x.front}</h3><p>tap to reveal</p></div><div class="card-face card-back"><span class="tag">for you</span><p>${x.back}</p></div></div></article>`).join('');
const smoothTo=id=>document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'});
q('#beginBtn').addEventListener('click',()=>smoothTo('birthday'));
qa('.card').forEach(card=>{const toggle=()=>card.classList.toggle('open');card.addEventListener('click',toggle);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle()}})});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});qa('.reveal').forEach(el=>observer.observe(el));
let started=false;function revealConfession(){if(started)return;started=true;const box=q('#confessionLines');SITE.confessionLines.forEach((text,i)=>{const el=document.createElement('div');el.className='confession-line';el.textContent=text;box.appendChild(el);setTimeout(()=>el.classList.add('show'),i*1150+350)});const d=SITE.confessionLines.length*1150+800;setTimeout(()=>{q('#finalConfession').textContent=SITE.confession;q('#finalConfession').classList.add('show')},d);setTimeout(()=>q('#permission').classList.add('show'),d+1600);setTimeout(()=>q('#birthdayEnd').classList.add('show'),d+2800)}
const confessionObserver=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)revealConfession()}),{threshold:.3});confessionObserver.observe(q('#confession'));
const sound=q('#soundToggle'),music=q('#music');if(SITE.music){music.src=SITE.music;sound.disabled=false;sound.addEventListener('click',async()=>{if(music.paused){await music.play();sound.innerHTML='♪ <span>sound on</span>'}else{music.pause();sound.innerHTML='♪ <span>sound off</span>'}})}
const backTop=q('#backTop');window.addEventListener('scroll',()=>backTop.classList.toggle('visible',scrollY>innerHeight*1.1),{passive:true});backTop.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));
if(!matchMedia('(prefers-reduced-motion: reduce)').matches){const hero=q('.hero-inner');window.addEventListener('scroll',()=>{if(scrollY<innerHeight){hero.style.transform=`translateY(${scrollY*.05}px)`;hero.style.opacity=String(Math.max(.2,1-scrollY/(innerHeight*.9))) }},{passive:true})}
